export type NichoConfig = {
  id: string;
  nome: string;
  emoji: string;
  descricao: string;
  unidadesPrincipais: string[];
  categoriasMateriais: string[];
  exemplosServicos: string[];
  exemplosMateriais: { nome: string; unidade: string; categoria: string }[];
  labelMaterial: string; // Como chamar "Material" neste nicho
  labelServico: string;  // Como chamar "Serviço" neste nicho
};

export const NICHOS: NichoConfig[] = [
  {
    id: "estetica_automotiva",
    nome: "Estética Automotiva",
    emoji: "🚗",
    descricao: "Lava-jato, polimento, higienização, cristalização e detalhamento",
    unidadesPrincipais: ["ml", "litro"],
    categoriasMateriais: ["Shampoo", "Cera", "Pré-lavagem", "Pretinho", "Silicone", "Microfibra"],
    exemplosServicos: ["Lavagem Simples", "Lavagem Completa", "Polimento", "Higienização Interna"],
    exemplosMateriais: [
      { nome: "Shampoo Automotivo", unidade: "litro", categoria: "Shampoo" },
      { nome: "Cera Líquida", unidade: "litro", categoria: "Cera" },
      { nome: "Pré-lavagem Desengordurante", unidade: "litro", categoria: "Pré-lavagem" },
    ],
    labelMaterial: "Produto",
    labelServico: "Serviço",
  },
  {
    id: "salao_beleza",
    nome: "Salão de Beleza",
    emoji: "💇",
    descricao: "Tintura, hidratação, escova, corte e tratamentos capilares",
    unidadesPrincipais: ["ml", "g"],
    categoriasMateriais: ["Tintura", "Oxidante", "Máscara", "Shampoo", "Condicionador", "Botox"],
    exemplosServicos: ["Corte Feminino", "Escova Progressiva", "Coloração", "Hidratação Profunda"],
    exemplosMateriais: [
      { nome: "Tintura Profissional", unidade: "g", categoria: "Tintura" },
      { nome: "Água Oxigenada 20vol", unidade: "ml", categoria: "Oxidante" },
      { nome: "Máscara Reconstrutora", unidade: "ml", categoria: "Máscara" },
    ],
    labelMaterial: "Produto",
    labelServico: "Procedimento",
  },
  {
    id: "barbearia",
    nome: "Barbearia",
    emoji: "✂️",
    descricao: "Corte masculino, barba, bigode, sobrancelha e tratamentos",
    unidadesPrincipais: ["ml", "g", "unidade"],
    categoriasMateriais: ["Creme de Barbear", "Pomada", "Tônico", "Lâmina", "Shampoo"],
    exemplosServicos: ["Corte Masculino", "Barba Completa", "Corte + Barba", "Pigmentação de Barba"],
    exemplosMateriais: [
      { nome: "Creme de Barbear", unidade: "ml", categoria: "Creme de Barbear" },
      { nome: "Pomada Modeladora", unidade: "g", categoria: "Pomada" },
      { nome: "Lâmina Descartável", unidade: "unidade", categoria: "Lâmina" },
    ],
    labelMaterial: "Produto",
    labelServico: "Serviço",
  },
  {
    id: "manicure_pedicure",
    nome: "Manicure & Pedicure",
    emoji: "💅",
    descricao: "Unhas em gel, acrigel, fibra, nail art e cuidados das unhas",
    unidadesPrincipais: ["ml", "g", "unidade"],
    categoriasMateriais: ["Esmalte", "Base", "Gel UV", "Acrigel", "Acetona", "Removedor"],
    exemplosServicos: ["Manicure Simples", "Pedicure Completa", "Unhas em Gel", "Nail Art"],
    exemplosMateriais: [
      { nome: "Esmalte", unidade: "ml", categoria: "Esmalte" },
      { nome: "Gel UV", unidade: "g", categoria: "Gel UV" },
      { nome: "Acetona", unidade: "ml", categoria: "Acetona" },
    ],
    labelMaterial: "Produto",
    labelServico: "Procedimento",
  },
  {
    id: "papelaria_impressao",
    nome: "Papelaria & Impressão",
    emoji: "🖨️",
    descricao: "Impressão digital, offset, adesivos, banners e personalizados",
    unidadesPrincipais: ["folha", "m²", "unidade", "ml"],
    categoriasMateriais: ["Papel", "Tinta", "Vinil", "Lona", "Acabamento"],
    exemplosServicos: ["Impressão A4", "Banner Lona", "Adesivo Recortado", "Cartão de Visita"],
    exemplosMateriais: [
      { nome: "Papel Couchê 150g A4", unidade: "folha", categoria: "Papel" },
      { nome: "Tinta Ciano", unidade: "ml", categoria: "Tinta" },
      { nome: "Vinil Adesivo", unidade: "m²", categoria: "Vinil" },
    ],
    labelMaterial: "Insumo",
    labelServico: "Trabalho",
  },
  {
    id: "pintura_predial",
    nome: "Pintura Predial",
    emoji: "🎨",
    descricao: "Pintura residencial e comercial, textura, grafiato e massa corrida",
    unidadesPrincipais: ["litro", "kg", "m²"],
    categoriasMateriais: ["Tinta", "Massa Corrida", "Primer", "Textura", "Selador"],
    exemplosServicos: ["Pintura Interna", "Pintura Fachada", "Textura Grafiato", "Massa Corrida"],
    exemplosMateriais: [
      { nome: "Tinta Acrílica 18L", unidade: "litro", categoria: "Tinta" },
      { nome: "Massa Corrida PVA", unidade: "kg", categoria: "Massa Corrida" },
      { nome: "Selador Acrílico", unidade: "litro", categoria: "Selador" },
    ],
    labelMaterial: "Material",
    labelServico: "Serviço",
  },
  {
    id: "marcenaria",
    nome: "Marcenaria & Carpintaria",
    emoji: "🪵",
    descricao: "Móveis planejados, reformas, restauração e trabalhos em madeira",
    unidadesPrincipais: ["m²", "metro", "unidade", "litro"],
    categoriasMateriais: ["Madeira", "MDF", "Cola", "Verniz", "Lixa", "Ferragem"],
    exemplosServicos: ["Armário Planejado", "Cozinha sob Medida", "Restauração de Móvel"],
    exemplosMateriais: [
      { nome: "MDF 15mm", unidade: "m²", categoria: "MDF" },
      { nome: "Verniz PU", unidade: "litro", categoria: "Verniz" },
      { nome: "Cola de Contato", unidade: "litro", categoria: "Cola" },
    ],
    labelMaterial: "Material",
    labelServico: "Trabalho",
  },
  {
    id: "costura_confeccao",
    nome: "Costura & Confecção",
    emoji: "🪡",
    descricao: "Roupa sob medida, bordado, conserto, uniformes e customização",
    unidadesPrincipais: ["metro", "unidade", "g"],
    categoriasMateriais: ["Tecido", "Linha", "Zíper", "Botão", "Entretela", "Elástico"],
    exemplosServicos: ["Vestido Sob Medida", "Ajuste de Roupa", "Uniforme", "Bordado"],
    exemplosMateriais: [
      { nome: "Tecido Algodão", unidade: "metro", categoria: "Tecido" },
      { nome: "Linha Poliéster", unidade: "unidade", categoria: "Linha" },
      { nome: "Zíper 20cm", unidade: "unidade", categoria: "Zíper" },
    ],
    labelMaterial: "Material",
    labelServico: "Trabalho",
  },
  {
    id: "mecanica_automotiva",
    nome: "Mecânica Automotiva",
    emoji: "🔧",
    descricao: "Revisão, troca de óleo, freios, suspensão e motor",
    unidadesPrincipais: ["litro", "unidade", "kg"],
    categoriasMateriais: ["Óleo", "Filtro", "Fluido", "Peça", "Graxa"],
    exemplosServicos: ["Troca de Óleo", "Revisão Completa", "Freios", "Alinhamento"],
    exemplosMateriais: [
      { nome: "Óleo Motor 5W30", unidade: "litro", categoria: "Óleo" },
      { nome: "Filtro de Óleo", unidade: "unidade", categoria: "Filtro" },
      { nome: "Fluido de Freio DOT4", unidade: "litro", categoria: "Fluido" },
    ],
    labelMaterial: "Peça / Produto",
    labelServico: "Serviço",
  },
  {
    id: "confeitaria_panificacao",
    nome: "Confeitaria & Panificação",
    emoji: "🎂",
    descricao: "Bolos, tortas, doces finos, salgados e pães artesanais",
    unidadesPrincipais: ["kg", "g", "litro", "ml", "unidade"],
    categoriasMateriais: ["Farinha", "Açúcar", "Manteiga", "Ovo", "Chocolate", "Creme"],
    exemplosServicos: ["Bolo Decorado", "Torta de Festa", "Doces Finos (12un)", "Salgados (50un)"],
    exemplosMateriais: [
      { nome: "Farinha de Trigo", unidade: "kg", categoria: "Farinha" },
      { nome: "Chocolate em Pó 50%", unidade: "kg", categoria: "Chocolate" },
      { nome: "Manteiga sem sal", unidade: "kg", categoria: "Manteiga" },
    ],
    labelMaterial: "Ingrediente",
    labelServico: "Produto",
  },
  {
    id: "pet_shop",
    nome: "Pet Shop & Banho e Tosa",
    emoji: "🐾",
    descricao: "Banho, tosa, hidratação e cuidados com animais domésticos",
    unidadesPrincipais: ["ml", "g", "unidade"],
    categoriasMateriais: ["Shampoo Pet", "Condicionador Pet", "Perfume", "Antipulgas", "Lâmina Tosa"],
    exemplosServicos: ["Banho Simples", "Banho + Tosa", "Tosa Higiênica", "Hidratação"],
    exemplosMateriais: [
      { nome: "Shampoo Neutro Pet", unidade: "ml", categoria: "Shampoo Pet" },
      { nome: "Condicionador Pet", unidade: "ml", categoria: "Condicionador Pet" },
      { nome: "Perfume Colônia Pet", unidade: "ml", categoria: "Perfume" },
    ],
    labelMaterial: "Produto",
    labelServico: "Serviço",
  },
  {
    id: "limpeza_conservacao",
    nome: "Limpeza & Conservação",
    emoji: "🧹",
    descricao: "Limpeza residencial, comercial, pós-obra e higienização",
    unidadesPrincipais: ["litro", "ml", "kg", "unidade"],
    categoriasMateriais: ["Desinfetante", "Detergente", "Alvejante", "Cera de Piso", "Pano"],
    exemplosServicos: ["Faxina Residencial", "Limpeza Pós-Obra", "Higienização Sofá", "Lavagem de Tapete"],
    exemplosMateriais: [
      { nome: "Desinfetante 5L", unidade: "litro", categoria: "Desinfetante" },
      { nome: "Detergente Neutro", unidade: "litro", categoria: "Detergente" },
      { nome: "Cera de Piso", unidade: "litro", categoria: "Cera de Piso" },
    ],
    labelMaterial: "Produto",
    labelServico: "Serviço",
  },
  {
    id: "serigrafia_estamparia",
    nome: "Serigrafia & Estamparia",
    emoji: "👕",
    descricao: "Camisetas, uniformes, brindes, sublimação e DTF",
    unidadesPrincipais: ["ml", "g", "unidade", "m²"],
    categoriasMateriais: ["Tinta Serigrafia", "Emulsão", "Tela", "Camiseta", "Transfer"],
    exemplosServicos: ["Camiseta Silk 1 cor", "Sublimação Caneca", "DTF", "Uniforme Bordado"],
    exemplosMateriais: [
      { nome: "Tinta Plastisol Preta", unidade: "kg", categoria: "Tinta Serigrafia" },
      { nome: "Emulsão Fotográfica", unidade: "kg", categoria: "Emulsão" },
      { nome: "Camiseta Branca Lisa", unidade: "unidade", categoria: "Camiseta" },
    ],
    labelMaterial: "Insumo",
    labelServico: "Serviço",
  },
  {
    id: "jardinagem_paisagismo",
    nome: "Jardinagem & Paisagismo",
    emoji: "🌿",
    descricao: "Corte de grama, poda, adubação, plantio e projetos",
    unidadesPrincipais: ["kg", "litro", "unidade", "m²"],
    categoriasMateriais: ["Adubo", "Herbicida", "Semente", "Terra", "Substrato"],
    exemplosServicos: ["Corte de Grama", "Poda de Árvore", "Adubação", "Plantio de Jardim"],
    exemplosMateriais: [
      { nome: "Adubo Granulado", unidade: "kg", categoria: "Adubo" },
      { nome: "Substrato Vegetal", unidade: "kg", categoria: "Substrato" },
      { nome: "Herbicida Concentrado", unidade: "litro", categoria: "Herbicida" },
    ],
    labelMaterial: "Insumo",
    labelServico: "Serviço",
  },
  {
    id: "outros",
    nome: "Outro / Personalizado",
    emoji: "⚙️",
    descricao: "Qualquer negócio que usa materiais + mão de obra. Configure como preferir.",
    unidadesPrincipais: ["unidade", "kg", "litro", "metro", "m²"],
    categoriasMateriais: ["Material A", "Material B", "Insumo", "Produto"],
    exemplosServicos: ["Serviço A", "Serviço B"],
    exemplosMateriais: [],
    labelMaterial: "Material",
    labelServico: "Serviço",
  },
];

export function getNichoById(id: string): NichoConfig | undefined {
  return NICHOS.find((n) => n.id === id);
}
